version: 0.2
phases:
  install:
    commands:
      - echo Installing dependencies...
      - pip install -r frontend/requirements.txt || true
  build:
    commands:
      - echo Build complete
artifacts:
  files:
    - "**/*"
  base-directory: frontend
